title: Introuduce Myself
author: Zhaohui
email: 2376102273@qq.com
description: > # this means to ignore newlines until "baseurl:"
 I have study about Github for 8 hours .I already have a litte knowledge about it.
 That's a wanderful experience.
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle
show_excerpts: true # set to false to remove excerpts on the homepage
 theme: minima
